//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InoviceProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InoviceConnection : DbContext
    {
        public InoviceConnection()
            : base("name=InoviceConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category_information> category_information { get; set; }
        public virtual DbSet<customer_information> customer_information { get; set; }
        public virtual DbSet<order_detail> order_detail { get; set; }
        public virtual DbSet<order_master> order_master { get; set; }
        public virtual DbSet<product_information> product_information { get; set; }
        public virtual DbSet<supplier_information> supplier_information { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
    }
}
