//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InoviceProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_detail
    {
        public decimal ORDER_ID { get; set; }
        public decimal PRODUCT_ID { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<decimal> UNIT_PRICE { get; set; }
    
        public virtual order_master order_master { get; set; }
        public virtual product_information product_information { get; set; }
    }
}
