//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InoviceProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_information
    {
        public product_information()
        {
            this.order_detail = new HashSet<order_detail>();
            this.order_master = new HashSet<order_master>();
        }
    
        public decimal PRODUCT_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> SUPPLIER_ID { get; set; }
        public Nullable<decimal> CATEGORY_ID { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<decimal> UNIT_PRICE { get; set; }
    
        public virtual category_information category_information { get; set; }
        public virtual ICollection<order_detail> order_detail { get; set; }
        public virtual supplier_information supplier_information { get; set; }
        public virtual ICollection<order_master> order_master { get; set; }
    }
}
