//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InoviceProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier_information
    {
        public supplier_information()
        {
            this.product_information = new HashSet<product_information>();
        }
    
        public decimal SUPPLIER_ID { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string POSTAL_CODE { get; set; }
        public string COUNTRY { get; set; }
        public string SUPPLIER_NAME { get; set; }
    
        public virtual ICollection<product_information> product_information { get; set; }
    }
}
